/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 2
        max_iteration: 8
        cube_side_length: 10.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"
        common:
            lid_topic:  "/scan_3D"
            imu_topic:  "/imu/data"

        preprocess:
            lidar_type: 4
            scan_line: 6 # ignored for lidar_type=4
            blind: 0.5

        initialization:
            cut_frame_num: 1 # must be positive integer
            orig_odom_freq: 15
            mean_acc_norm: 9.805 # m/s^2
            online_refine_time: 20.0
            data_accum_length: 400.0
            Rot_LI_cov: [ 0.0005, 0.0005, 0.0005 ]
            Trans_LI_cov: [ 0.0001, 0.0001, 0.0001 ]

        mapping:
            filter_size_surf: 0.02
            filter_size_map: 0.08
            gyr_cov: 20.0
            acc_cov: 2.0
            b_acc_cov: 1.0e-4 
            b_gyr_cov: 1.0e-4
            det_range: 2.0

        publish:
            path_en:  true
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

