/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 3
        max_iteration: 3
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"
        common:
            lid_topic:  "/os_cloud_node/points"
            imu_topic:  "/os_cloud_node/imu"

        preprocess:
            lidar_type: 3                # Ouster LiDAR
            scan_line: 64
            blind: 4.0
            feature_extract_en: false

        initialization:
            cut_frame: false
            cut_frame_num: 1 # must be positive integer
            orig_odom_freq: 10
            mean_acc_norm: 9.805
            online_refine_time: 15.0
            data_accum_length: 700.0
            Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
            Trans_LI_cov: [ 0.0001, 0.0001, 0.0001 ]

        mapping:
            filter_size_surf: 0.5
            filter_size_map: 0.5
            gyr_cov: 40.0
            acc_cov: 2.0
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            det_range: 150.0

        publish:
            path_en:  true
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.